### ISSUE TITLE
Interesting Project

### ISSUE THREAD

**Issue by idkjs** [coder-ka/aim#1]
In the `Readme.md` you say you have a demo. Can you update with a link or example?

Thank you for sharing your work.

**Comment by coder-ka** [comment]
Hello @idkjs .
I'm glad to your interesting to my project.

I wrote the README.
It is written in Japanese because I'm not good at writing English.
Please read it using Google Translation or something else.

I made an example here.

https://github.com/coder-ka/aim-example

Feel free to ask anything about Aim and the example.
